@startuml

hide footbox
title Fase di Scrutinio
participant "Autorità\nElettorale (AE)" as AE #a0d7cc
participant "Bacheca Pubblica\n(BP)" as BP #d8be94

note over AE, BP: lo scrutinio inizia a urne chiuse\nSulla bacheca pubblica\nci sono i blocchi contenenti le singole triple (i, C_voto, C_k, IV, ricevuta)

note right of AE: per ogni entry (i, C_voto, C_k, IV) con identificatore i:
AE -> AE : k_AES_i = Dec_RSA-OAEP(sk_AE_enc, C_k)\nvoto_i = Dec_AES-CBC(k_AES, IV_s, C_voto)

AE -> AE: compone la entry (i, voto, k, IV) per la tabella da pubblicare

note right of AE: calcola l'esito dell'elezione
AE -> AE: somma i voti per ciascuna opzione\ndella lista chiusa

note right of AE: costruisce l'albero per la verifica individuale con foglie H(B ||s)
AE -> AE: costruisce il suo MerkleTree

note right of AE: caricamento delle informazioni finali firmate con sk_AE_sig:\n- triple (i, voto, k_AES)\n- totali per opzione\n- radice di Merkle sulle foglie H(B || s)
AE -> BP: pubblica risultato

@enduml